# Simplified CI workflow for msdf-bmfont-xml
# Tests across all platforms using preloaded binaries

name: Node.js CI

on:
  push:
    branches: [ master, major-dependency-updates ]
  pull_request:
    branches: [ master, major-dependency-updates ]
  workflow_dispatch:

env:
  # Environment variables to disable update notifications
  DISABLE_UPDATE_NOTIFIER: true
  NO_UPDATE_NOTIFIER: true
  CI: true

jobs:
  test:
    name: Test ${{ matrix.platform }}
    runs-on: ${{ matrix.runs-on }}
    
    strategy:
      fail-fast: false
      matrix:
        include:
          - platform: Windows
            runs-on: windows-latest
          - platform: macOS Intel
            runs-on: macos-13 # only 13 available for free intel mac on OSS project
          - platform: macOS ARM64
            runs-on: macos-latest
          - platform: Linux x64
            runs-on: ubuntu-latest
          - platform: Linux ARM64
            runs-on: ubuntu-24.04-arm
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Setup Node.js 24.x
      uses: actions/setup-node@v4
      with:
        node-version: 24.x
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci --prefer-offline --no-audit --no-fund
    
    - name: Run tests
      run: npm test
